name: Mark and Close Stale Pull Requests

on:
  schedule:
    - cron: '41 2 * * *'  # Runs at 02:41 UTC every day.
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: -1         # Do not stale Issues
          days-before-issue-close: -1         # Do not close Issues
          days-before-pr-stale: 7             # Number of days of inactivity before a PR is marked stale
          days-before-pr-close: 7             # Number of days after being marked stale before a PR is closed
          stale-pr-message: 'ğŸ‘‹ Hey there! Just noticed this PR has been quiet for a week. We miss your updates! If there is no activity in the next week, we will need to close it for housekeeping. ğŸ˜ŠğŸ§¹ Fixes #<Issue Number>'
          stale-pr-label: 'stale'          # Label to apply to stale PRs
          close-pr-message: 'ğŸšª We are doing a little housekeeping and noticed this PR has been quiet for a while. We are going to close it for now. If you are ready to pick this up again, please feel free to open a new PR or reach out to us, and we will be happy to help you reopen this one! ğŸ˜„ğŸ‘ Fixes #<Issue Number>'
          operations-per-run: 30           # Maximum number of operations per run
